WIP: Revert "tmp: remove breaking change to variable `CC`"
This reverts commit cb6cd1859df2841586145dc76efb6163f7f55ac8.

error:
```
libc_impl.c:2935:5: error: call to undeclared function '__assert'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```

`ziglang/zig` issue submitted at https://github.com/ziglang/zig/issues/17887